# Generated by Django 3.2.6 on 2021-08-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
