# Generated by Django 3.2.7 on 2021-09-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(default='Python', max_length=100),
            preserve_default=False,
        ),
    ]
