# Generated by Django 3.2.7 on 2021-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(),
        ),
    ]
